### ISSUE TITLE
Missing doctype

### ISSUE THREAD

**Issue by jxu** [Dudemanguy/blog#1]
I read your recent blogpost about Wayland and wanted to see how you achieved the ancient website look. Probably unintentionally, without a doctype tag firefox warns you are in IE quirks mode. You probably should use `<html>` tags too unless you want to be very minimalist.

**Comment by Dudemanguy** [comment]
Thanks. Should be fixed now. Webshit is hard.

**Comment by jxu** [comment]
I thought about making a minimalist (in source, not just visuals) blog too, either with a Markdown generator or pure HTML (with editor shortcuts to make things like inserting formatting tags easier). I wanted it to be javascript free, so if I ever put in math equations I'll have to prerender them, which would add some complexity to the publishing process.

**Comment by jxu** [comment]
<link> and <meta> should go inside <head>. I have never seen them outside of <head> so maybe is technically valid.
