### ISSUE TITLE
Consider adding an RSS feed

### ISSUE THREAD

**Issue by veilm** [Dudemanguy/blog#2]
What do you think about the idea of adding an [RSS](https://en.wikipedia.org/wiki/RSS) feed to the blog? This would make it possible for people who are interested to be automatically "pinged" when you make a new post, meaning that they don't have to check the site manually for new updates. It wouldn't add any web bloat; it would just be a link to a .xml or .atom file.

Regarding visual placement, I don't think it would damage the appearance of the site or anything. For example,
![1](https://user-images.githubusercontent.com/57649592/186288274-fd1edb8e-9009-4253-a8c7-b231ed067595.png)
still looks nice/minimal and also makes the footer more consistent with the header.

Regarding implementation, the most standard way would be to use a script like [sup](https://github.com/LukeSmithxyz/lb/blob/master/sup), which would copy a formatted version of the post into the XML file. I'm assuming you're already using a script for creating HTML templates and updating the "recent posts" section in index.html, so integrating it there would remove the need for any manual usage. If you're not using a script, I could try doing some research about git hooks and write a wrapper script that would look at docs/posts/ and add things automatically before commiting, or something similar, if you're open to that.

If that's annoying, another option is to simply link to [GitHub's commit feed](https://github.com/Dudemanguy/blog/commits/master.atom). This is less convenient for the viewer, though, since the URL would take them to the diff of the commit instead of directly to the post on the site:
![2](https://user-images.githubusercontent.com/57649592/186288577-2839dad2-d405-4a55-a151-2205ad32eb96.png)

If you're interested, I'd be happy to provide further explanations/examples/etc. if that would be helpful. If you're not interested, that's fine too. I don't want to be annoying for no reason; I just thought that an RSS feed could be useful.

**Comment by Dudemanguy** [comment]
An RSS feed is definitely a good idea. I'm subscribed to a few myself.

**Comment by Dudemanguy** [comment]
Took me a while to get around to doing this, but there is one now.
