### ISSUE TITLE
Invalid link element location

### ISSUE THREAD

**Issue by jxu** [Dudemanguy/blog#3]
Since I was looking through the HTML, I noticed you put `<link>` directly under `<html>` which is not permitted https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html 

https://validator.w3.org/ gives a non-straightforward error "Error: Start tag head seen but an element of the same type was already open." Good tool to use btw.

**Comment by veilm** [comment]
``<meta>`` is also not supposed to be directly in ``<html>``, right? Additionally, I see other errors like
```html
<div class="footer">
	<a class="navitem" href="https://github.com/Dudemanguy">Github</a>
	<a class="navitem" href="https://github.com/Dudemanguy/blog">Website Source</a>
</footer>
```
If I have time later, I could maybe go through each HTML file in the w3 validator and make a PR for a final cleanup, since reviewing changes would probably be faster/easier than making them here.
Edit: Never mind, Dudemanguy already made the changes

These are the kind of issues that would be trivial to solve when using static site generators, which have a DRY structure

**Comment by jxu** [comment]
> These are the kind of issues that would be trivial to solve when using static site generators, which have a DRY structure

That's true, but there is a certain minimalism in not using a static site generator like Jekyll, and once the validation errors are solved the template only needs to be changed for design purposes. The only reason I looked at the HTML was because this blog did plain HTML, but I haven't ruled out a simple templating system, even as simple as bash and a makefile.

**Comment by veilm** [comment]
> > These are the kind of issues that would be trivial to solve when using static site generators, which have a DRY structure
> 
> That's true, but there is a certain minimalism in not using a static site generator like Jekyll, and once the validation errors are solved the template only needs to be changed for design purposes. The only reason I looked at the HTML was because this blog did plain HTML, but I haven't ruled out a simple templating system, even as simple as bash and a makefile.

The way I see it is that the fewer lines of code your repository contains, the more minimalim it is[0], but I can see where you're coming from: it[1] would add a dependency for building your website, so the total lines of code of software on the development computer would be much higher

0: in this contex; for normal software it's less about lines of code and more about included features
1: I haven't used Jekyll specifically but I have some experience with Hugo

**Comment by jxu** [comment]
Writing plain HTML is also an excuse to get more familiar with HTML and the DOM, which I don't interact with when using Jekyll. There is maybe some nostalgic factor somehow too.

**Comment by veilm** [comment]
That's true. If someone's blog is their only exposure to writing websites and they use markdown (or whatever other format the static site generator uses) for it, the skill of HTML, which can be pretty useful, will gradually be lost.
